name: demo 
on:
  [push]
jobs:
  print_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print a message to console
      run: |
        echo "Hello, GitHub Actions!"
        echo "This is another message"
